name: CD

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag based on commit sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891377072964:role/GithubActionsRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build Docker image and push to ECR
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ${{vars.ECR_REGISTRY}}/${{vars.IMAGE_NAME}}:latest
            ${{vars.ECR_REGISTRY}}/${{vars.IMAGE_NAME}}:${{env.SHORT_SHA}}

      - name: Create new ECS task definition revision
        run: |
          jq --arg IMG "${{ vars.ECR_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ env.SHORT_SHA }}" \
            '.containerDefinitions[0].image=$IMG' task-definition-template.json > task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: backend-service
          cluster: web-app-cluster
          wait-for-service-stability: true