name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha.substring(0,7) }}

    steps:
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from ECR
        run: docker pull ${{ vars.ECR_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ env.IMAGE_TAG }}