name: backend-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Print docker version
        run: docker --version

      - name: Login to AWS ECR
        uses: docker/login-action@v4
        with:
          registry: 975049976794.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}