name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to rollback (staging or production)"
        required: true
        type: choice
        options:
          - staging
          - production

      image_tag:
        description: "Image tag - short SHA to rollback to (7 chars)"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  staging-rollback:
    if: github.event.inputs.environment == "staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: staging.maissen.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423409202:role/GithubActionsRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECS task definition for rollback
        run: |
          jq --arg IMG "${{ vars.ECR_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}" \
            '.containerDefinitions[0].image=$IMG' task-definition-staging-template.json > task-definition.json

      - name: Deploy rollback to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: ${{ vars.STAGING_ECS_SERVICE }}
          cluster: ${{ vars.STAGING_ECS_CLUSTER }}
          wait-for-service-stability: true

  prod-rollback:
    if: github.event.inputs.environment == "production"
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: maissen.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423409202:role/GithubActionsRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECS task definition for rollback
        run: |
          jq --arg IMG "${{ vars.ECR_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}" \
            '.containerDefinitions[0].image=$IMG' task-definition-prod-template.json > task-definition.json

      - name: Deploy rollback to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: ${{ vars.PROD_ECS_SERVICE }}
          cluster: ${{ vars.PROD_ECS_CLUSTER }}
          wait-for-service-stability: true